version: '3'
services:
  backend_service:
    build:
      context: backend/
    ports:
     - "4000:4000"
  frontend_service:
    build:
      context: frontend/
    ports:
     - "3000:3000"
    depends_on:
     - backend_service